dataset_dir: /home/mingxi/data/mimicgen/raw_datasets/core
output_dir: /home/mingxi/data/mimicgen/squashfs_datasets
output_folder: stack_d1
dataset_file: stack_d1.hdf5
num_demos: 500
num_workers: 16
env_xml_filename: table_arena.xml
camera_obs_modality: separate
done_mode: 2
camera_resolution: 128